version: 2

sources:
  - name: public
    tables:
      - name: orders
      - name: products

models:
  - name: product_order_model
    description: "An order model includes detailed product information."
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: product_category_total_sale_model
    description: "Aggregate all orders by grouping by products category and calculate the sale total."
    columns:
      - name: category
        description: "The type of products"
        tests:
          - unique
          - not_null

  - name: user_total_sale_model
    description: "Aggregate all orders by grouping by user id and calculate the sale total."
    columns:
      - name: user_id
        description: "The id of custom"
        tests:
          - unique
          - not_null